### ISSUE TITLE
JavaScript parse error (scripts need to be valid ECMAScript 5): Parse error: Unterminated string literal in file 'MediaWiki:Gadget-Twinkle.js' on line 12

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle-starter#27]
Caused by https://github.com/wikimedia-gadgets/twinkle-starter/commit/28c846bac98dc44c30df96b92361d075a8c05d61. Needs to be looked into.

**Comment by kenrick95** [comment]
so I tried out this starter on idwiki, and encountered this issue.

My trick here is to prettify the built codes and use it there: https://id.wikipedia.org/wiki/MediaWiki:Gadget-TwinkleV3.js

![Screenshot 2021-12-22 225020](https://user-images.githubusercontent.com/3090380/147111531-d5e076e1-c6e4-4dda-a97d-3557a0fdd4aa.png)

and the mediawiki error message points to this line in the gadget

![Screenshot 2021-12-22 225009](https://user-images.githubusercontent.com/3090380/147111519-c953301a-d254-4907-adc7-0bea3ee6fa8c.png)

which apparently caused by this RegExp in orange-18n:

https://github.com/wikimedia-gadgets/orange-i18n/blob/2a13edf418cab7beb9efb5ca995bffb758dc101b/src/emitter.js#L13-L21

**Comment by siddharthvp** [comment]
Upstream bug reports:
- https://phabricator.wikimedia.org/T298386
- https://phabricator.wikimedia.org/T299537

Also relevant is https://phabricator.wikimedia.org/T75714 since if that is solved, this issue will be resolved.

**Comment by siddharthvp** [comment]
Belated note: https://phabricator.wikimedia.org/T298386 has been resolved, this should not be occurring now.

**Comment by siddharthvp** [comment]
In case it does occur, there's also the option of using `|requiresES6` in the gadget definition which disables the MW script validator altogether. JS in non-ES6 browsers is anyway not supported at all by MediaWiki now ([T178356](https://phabricator.wikimedia.org/T178356)).
